import { Bookinfo } from './bookinfo';

export const BOOKS: Bookinfo[] = [
    {
        bno: 'B00001',
        bname: '111',
        burl: '12334',
        author: '1a',
        briefintro: '121212',
        chapcount: 11,
        insuser: '',
        instime: '',
        upduser: '',
        updtime: '',
    },
    {
        bno: 'B00002',
        bname: '112',
        burl: '22334',
        author: '2a',
        briefintro: '221212',
        chapcount: 12,
        insuser: '',
        instime: '',
        upduser: '',
        updtime: '',
    },
    {
        bno: 'B00003',
        bname: '113',
        burl: '32334',
        author: '3a',
        briefintro: '321212',
        chapcount: 13,
        insuser: '',
        instime: '',
        upduser: '',
        updtime: '',
    },
];
